
// This file has been generated by the GUI designer. Do not modify.
namespace CGTK_MySQL
{
	public partial class WindowAction
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget CGTK_MySQL.WindowAction
			this.Name = "CGTK_MySQL.WindowAction";
			this.Title = global::Mono.Unix.Catalog.GetString("ventanaAcciones");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
