
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.Button categoria;

	private global::Gtk.Button productos;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.categoria = new global::Gtk.Button();
		this.categoria.CanFocus = true;
		this.categoria.Name = "categoria";
		this.categoria.UseUnderline = true;
		this.categoria.Label = global::Mono.Unix.Catalog.GetString("Categorías");
		this.vbox1.Add(this.categoria);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.categoria]));
		w1.Position = 0;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.productos = new global::Gtk.Button();
		this.productos.CanFocus = true;
		this.productos.Name = "productos";
		this.productos.UseUnderline = true;
		this.productos.Label = global::Mono.Unix.Catalog.GetString("Productos");
		this.vbox1.Add(this.productos);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.productos]));
		w2.Position = 1;
		w2.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.categoria.Clicked += new global::System.EventHandler(this.OnCategoriaClicked);
		this.productos.Clicked += new global::System.EventHandler(this.OnProductosClicked);
	}
}
